// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// predBMAcpp
NumericMatrix predBMAcpp(NumericMatrix SurvMat, NumericMatrix LpMat, NumericVector WtVec);
RcppExport SEXP glmBfp_predBMAcpp(SEXP SurvMatSEXP, SEXP LpMatSEXP, SEXP WtVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type SurvMat(SurvMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type LpMat(LpMatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type WtVec(WtVecSEXP);
    rcpp_result_gen = Rcpp::wrap(predBMAcpp(SurvMat, LpMat, WtVec));
    return rcpp_result_gen;
END_RCPP
}
